# Main release version
AIONYX_VER_MAIN = "2026.1"

# Set to "release" for major releases and "update-1" for update releases
AIONYX_VER_UPDATE = "snapshot"

# This will be set in local.conf for CI builds
AIONYX_VER_BUILD ?= "${@'${METADATA_REVISION}' if d.getVar('METADATA_REVISION') != '<unknown>' else 'unknown'}"

# Aionyx version
AIONYX_VERSION = "${AIONYX_VER_MAIN}"