require conf/distro/poky.conf

# Reset the default set in poky, we want to set it ourselves in aionyx-features
unset INIT_MANAGER

require conf/distro/include/aionyx-features.conf
require conf/distro/include/aionyx-mirrors.conf
require conf/distro/include/aionyx-version.conf
#include conf/distro/include/aionyx-feed.conf

DISTRO = "aionyx"
DISTRO_NAME = "AionyxOS"

# Follow the Poky format of <Version>+<type>-<date>
DISTRO_VERSION = "${AIONYX_VER_MAIN}+${AIONYX_VER_UPDATE}-${AIONYX_VER_BUILD}"

SDK_VENDOR = "-aionyx"
SDK_VERSION := "${@'${AIONYX_VER_MAIN}'.replace('snapshot-${DATE}','snapshot')}"

MAINTAINER = "NetTimeLogic GmbH <contact@nettimelogic.com>"

TARGET_VENDOR = "-ntl"

SANITY_TESTED_DISTROS:append = " \
	centos-7.4 \n \
	centos-7.5 \n \
	centos-7.6 \n \
	centos-7.7 \n \
	centos-7.9 \n \
	centos-8 \n \
	centos-8.2 \n \
	centos-8.3 \n \
	centos-8.4 \n \
	centos-8.5 \n \
	centos-8.6 \n \
	rhel-7.4 \n \
	rhel-7.5 \n \
	rhel-7.6 \n \
	rhel-7.7 \n \
	rhel-7.9 \n \
	rhel-8.2 \n \
	rhel-8.3 \n \
	rhel-8.4 \n \
	rhel-8.5 \n \
	rhel-8.6 \n \
	almalinux-8.10 \n \
	almalinux-9.4 \n \
	almalinux-9.5 \n \
	"

# Packages to skip
SKIP_RECIPE[distro-feed-configs] = "Not supported, see aionyx-image-common.inc for feed config."

# Verify the user's configuration is valid
#INHERIT += "aionyx-externalsrc"

# Add alternative mirrors for some components
INHERIT+="aionyx-mirrors"

# Do not include clang in generated SDKs
CLANGSDK ?= "0"
